# This strict rubocop config should be used before submiting PR and should pass
# Doesn't include:
# - specs


AllCops:
  # Include gemspec and Rakefile
  Include:
    - 'app/**/*.rb'
    - 'config/**/*.rb'
    - 'lib/**/*.rb'
    - 'lib/**/*.rake'
  Exclude:
    - 'vendor/**/*'
    - 'db/**/*.rb'
    - 'bin/**/*'
    - 'lib/**/*.rake'
  RunRailsCops: true
  DisplayCopNames: true
  StyleGuideCopsOnly: false

require: rubocop-rspec

Metrics/LineLength:
  Max: 100
  Exclude:
    - 'spec/**/*.rb'
    - 'config/routes/**/*.rb'

Metrics/AbcSize:
  Max: 20
  Enabled: false

Metrics/MethodLength:
  Max: 15
  Enabled: false
  Exclude:
    - 'spec/**/*.rb'


Style/Documentation:
  Include:
    - 'app/**/*.rb'
  Exclude:
    - 'app/controllers/**/*.rb'
    - 'app/helpers/**/*.rb'
    - 'app/mailers/**/*.rb'
    - 'app/views/**/*.rb'
    - 'spec/**/*.rb'

Style/ClassAndModuleChildren:
  Exclude:
    - 'app/controllers/**/*.rb'

Style/BarePercentLiterals:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MultilineBlockLayout:
  Exclude:
    - 'spec/**/*'

Style/MultilineTernaryOperator:
  Enabled: false

Style/BlockEndNewline:
  Exclude:
    - 'spec/**/*'

Style/PredicateName:
  Exclude:
    - 'app/decorators/**/*.rb'

Style/TrivialAccessors:
  AllowPredicates: true

Style/MultilineBlockLayout:
  Exclude:
    - 'spec/**/*.rb'

Style/WordArray:
  Exclude:
    - 'spec/**/*.rb'

Style/Semicolon:
  Exclude:
    - 'spec/**/*.rb'

Style/Proc:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

